version: '3'
services:
  agile_config_admin:
    image: "kklldog/agile_config"
    ports:
      - "15000:5000"
    networks:
      - net0
    volumes:
      - /etc/localtime:/etc/localtime
    environment:
      - TZ=Asia/Shanghai
      - adminConsole=true
      - cluster=true
      - db__provider=mysql
      - db__conn=Database=configcenter;Data Source=yourip;User Id=root;Password=123456;port=3306;Allow User Variables=true;AllowPublicKeyRetrieval=true
networks:
  net0: